import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Nav
    nav_marketplace: 'Marketplace',
    nav_portfolio: 'Portfolio',
    nav_my_account: 'My Account',
    nav_business_account: 'Business Account',
    nav_secondary: 'Secondary Market',
    nav_my_projects: 'My Projects',
    nav_create: 'Create Offering',
    nav_admin: 'Admin Dashboard',
    nav_signin: 'Sign In',
    nav_get_started: 'Get Started',
    nav_logout: 'Logout',

    // Auth
    auth_sign_in: 'Sign In',
    auth_create_account: 'Create Account',
    auth_email: 'Email',
    auth_password: 'Password',
    auth_full_name: 'Full Name',
    auth_account_type: 'Account Type',
    auth_investor: 'Investor',
    auth_business: 'Business',
    auth_tagline: 'Where Capital Meets Opportunity',
    auth_subtitle: 'A curated marketplace for digital investment offerings — transparent, rated, and automated.',
    auth_feature_1: 'Automated interest calculations & payouts',
    auth_feature_2: 'Verified businesses with transparency ratings',
    auth_feature_3: 'Secondary market — buy & sell positions',
    auth_demo: 'Demo accounts',
    auth_wait: 'Please wait...',
    auth_error_generic: 'Something went wrong',
    auth_demo_failed: 'Demo login failed',

    // Marketplace
    mkt_title: 'Investment',
    mkt_title_2: 'Marketplace',
    mkt_active: 'active offerings',
    mkt_avg_return: 'avg annual return',
    mkt_list_offering: 'List an Offering',
    mkt_search: 'Search offerings...',
    mkt_filters: 'Filters',
    mkt_sort_newest: 'Newest First',
    mkt_sort_rate_desc: 'Highest Return',
    mkt_sort_rate_asc: 'Lowest Return',
    mkt_sort_funded: 'Most Funded',
    mkt_category: 'Category',
    mkt_risk: 'Risk Level',
    mkt_frequency: 'Payout Frequency',
    mkt_no_results: 'No offerings match your filters',
    mkt_funded: 'Funded',
    mkt_investors: 'investors',
    mkt_annual_return: 'annual return',
    mkt_min: 'Min',
    mkt_reviews: 'reviews',
    mkt_all: 'All',

    // Offering card
    card_risk_low: 'low risk',
    card_risk_medium: 'medium risk',
    card_risk_high: 'high risk',

    // Create Offering
    create_title: 'Create',
    create_title_2: 'Investment Offering',
    create_subtitle: 'List your project and attract investors with transparent terms.',
    step_basic: 'Basic Info',
    step_financial: 'Financial Terms',
    step_files: 'Files & Media',
    step_review: 'Review',
    step_payment: 'Payment',
    create_project_name: 'Project Name',
    create_project_name_hint: 'A clear, professional title for your investment offering',
    create_description: 'Description',
    create_description_hint: 'Describe the project, its goals, and why investors should trust it',
    create_description_placeholder: 'Provide a detailed description of your investment offering...',
    create_category: 'Category',
    create_risk: 'Risk Level',
    create_duration: 'Duration (months)',
    create_duration_hint: 'How long is this investment offering open?',
    create_payout_freq: 'Payout Frequency',
    create_interest_rate: 'Annual Interest Rate (%)',
    create_interest_hint: 'The yearly return percentage offered to investors',
    create_pool: 'Total Pool Size ($)',
    create_pool_hint: 'Maximum capital to raise',
    create_min_inv: 'Min Investment ($)',
    create_max_inv: 'Max Investment per Investor ($)',
    create_max_inv_hint: 'Optional — leave blank for no limit',
    create_files_title: 'Files & Media',
    create_files_subtitle: 'Upload presentations, visuals, and supporting documents. These build investor trust.',
    create_drop: 'Drop files or click to upload',
    create_drop_hint: 'PDF, PPT, PPTX, PNG, JPG, GIF · Max 20MB each',
    create_files_note: 'Files are optional but significantly increase investor confidence. Presentations and detailed financials are recommended.',
    create_review_title: 'Review Your Offering',
    create_submit: 'Submit Offering',
    create_submitting: 'Creating...',
    create_success_title: 'Offering Created!',
    create_success_sub: 'Your investment offering has been submitted for review. It will appear on the marketplace once approved.',
    create_my_projects: 'My Projects',
    create_view_offering: 'View Offering',
    create_review_note: 'Your offering will be reviewed by our team before going live on the marketplace.',
    create_payment_subtitle: 'Platform fees for listing and maintaining your investment offering on the marketplace.',
    create_annual_fee: 'Annual Platform Fee',
    create_per_year: 'per year',
    create_platform_fee: 'Platform Commission',
    create_of_raised: 'of amount raised',
    create_payment_info: 'Payment Wallet Address',
    create_payment_note: 'You will be prompted to send payment to this wallet address during checkout.',
    btn_continue: 'Continue',
    btn_back: 'Back',
    preview_title: 'Return Preview (per $1,000 invested)',
    preview_per_month: 'Per month',
    preview_per_quarter: 'Per quarter',
    preview_per_year: 'Per year',
    preview_annual: 'Annual return',
    preview_compounded: '12mo compounded',

    // Offering detail
    detail_about: 'About This Offering',
    detail_docs: 'Documents & Presentations',
    detail_ratings: 'Investor Ratings',
    detail_rate_btn: 'Rate This Project',
    detail_no_ratings: 'No ratings yet — be the first to invest and review.',
    detail_invest_btn: 'Invest Now →',
    detail_signin_btn: 'Sign In to Invest',
    detail_processing: 'Processing...',
    detail_success: 'Investment Confirmed!',
    detail_success_sub: 'Your position has been opened.',
    detail_view_portfolio: 'View Portfolio',
    detail_verified: 'Verified Offering',
    detail_verified_sub: 'Business identity & financials reviewed',
    detail_fully_funded: 'FULLY FUNDED',
    detail_inactive: 'This offering is not currently accepting investments.',
    detail_annual_rate: 'Annual interest rate',
    detail_duration: 'Duration',
    detail_investors: 'Investors',
    detail_yields: 'yields',
    detail_funded_progress: 'Funding Progress',
    detail_pool_remaining: 'Pool Remaining',
    detail_payout: 'Payout',
    detail_min_investment: 'Min Investment',
    detail_est_annual: 'Est. annual return',
    detail_per_period: 'Per',
    detail_submit_rating: 'Submit Rating',
    detail_payout_reliability: 'Payout Reliability',
    detail_transparency: 'Transparency',
    detail_overall: 'Overall Satisfaction',
    detail_feedback_placeholder: 'Share your experience (optional)...',
    detail_breadcrumb: 'Marketplace',

    // Portfolio
    portfolio_title: 'My',
    portfolio_title_2: 'Portfolio',
    portfolio_subtitle: 'Track your investments, earnings, and upcoming payouts.',
    portfolio_total_invested: 'Total Invested',
    portfolio_value: 'Portfolio Value',
    portfolio_earned: 'Total Earned',
    portfolio_roi: 'Overall ROI',
    portfolio_positions: 'Active Positions',
    portfolio_no_investments: 'No active investments.',
    portfolio_browse: 'Browse the marketplace →',
    portfolio_upcoming: 'Upcoming Payouts',
    portfolio_invested: 'invested',
    portfolio_current: 'current value',
    portfolio_earned_col: 'earned',
    portfolio_list_btn: 'List',
    portfolio_list_title: 'List on Secondary Market',
    portfolio_list_sub: 'Set your asking price for this investment position. Other investors can buy it.',
    portfolio_asking: 'Asking Price ($)',
    portfolio_asking_placeholder: 'Enter asking price',
    portfolio_cancel: 'Cancel',
    portfolio_list_sale: 'List for Sale',

    // My Projects
    my_title: 'My',
    my_title_2: 'Offerings',
    my_subtitle: 'Manage your investment listings.',
    my_new: 'New Offering',
    my_no_offerings: 'No offerings yet',
    my_no_sub: 'Create your first investment offering to start raising capital.',
    my_create: 'Create Offering',
    my_annual_rate: 'annual rate',
    my_investors: 'investors',

    // Secondary market
    sec_title: 'Secondary',
    sec_title_2: 'Market',
    sec_subtitle: 'Buy and sell existing investment positions from other investors.',
    sec_no_listings: 'No listings available',
    sec_no_sub: 'Check back later or list your own positions from your portfolio.',
    sec_asking: 'Asking Price',
    sec_original: 'Original',
    sec_current: 'Current Value',
    sec_interest: 'Interest Rate',
    sec_buy: 'Buy for',
    sec_buying: 'Purchasing...',
    sec_listed_by: 'Listed by',

    // Admin
    admin_title: 'Admin',
    admin_title_2: 'Dashboard',
    admin_subtitle: 'Monitor the platform — projects, users, and payouts.',
    admin_tab_overview: 'Overview',
    admin_tab_projects: 'Projects',
    admin_tab_users: 'Users',
    admin_tab_payouts: 'Payouts',
    admin_total_users: 'Total Users',
    admin_active_projects: 'Active Projects',
    admin_total_capital: 'Total Capital',
    admin_pending_payouts: 'Pending Payouts',
    admin_recent_projects: 'Recent Projects',
    admin_all_projects: 'All Projects',
    admin_all_users: 'All Users',
    admin_all_payouts: 'All Payouts',
    admin_pending: 'Pending',
    admin_processed: 'Processed',
    admin_project_col: 'Project',
    admin_rate_col: 'Rate',
    admin_funded_col: 'Funded',
    admin_investors_col: 'Investors',
    admin_status_col: 'Status',
    admin_actions_col: 'Actions',
    admin_active_btn: 'Active',
    admin_suspend_btn: 'Suspend',
    admin_restore_btn: 'Restore',
    admin_process_btn: 'Process',
    admin_fail_btn: 'Fail',
    admin_of: 'of',
    admin_total: 'total',
    admin_due: 'due',

    // Common
    loading: 'Loading...',
    status_active: 'Active',
    status_pending: 'Pending',
    status_closed: 'Closed',
    status_suspended: 'Suspended',
    status_processed: 'Processed',
    status_failed: 'Failed',
    risk_low: 'low',
    risk_medium: 'medium',
    risk_high: 'high',
    freq_monthly: 'monthly',
    freq_quarterly: 'quarterly',
    freq_annual: 'annual',
    cat_all: 'All',
    month: 'months',
    copyright: '© 2026 · Investment Marketplace · Regulated Digital Offerings Platform',
  },

  es: {
    // Nav
    nav_marketplace: 'Mercado',
    nav_portfolio: 'Portafolio',
    nav_my_account: 'Mi Cuenta',
    nav_business_account: 'Cuenta de Empresa',
    nav_secondary: 'Mercado Secundario',
    nav_my_projects: 'Mis Proyectos',
    nav_create: 'Crear Oferta',
    nav_admin: 'Panel Admin',
    nav_signin: 'Iniciar Sesión',
    nav_get_started: 'Comenzar',
    nav_logout: 'Cerrar Sesión',

    // Auth
    auth_sign_in: 'Iniciar Sesión',
    auth_create_account: 'Crear Cuenta',
    auth_email: 'Correo Electrónico',
    auth_password: 'Contraseña',
    auth_full_name: 'Nombre Completo',
    auth_account_type: 'Tipo de Cuenta',
    auth_investor: 'Inversor',
    auth_business: 'Empresa',
    auth_tagline: 'Donde el Capital Encuentra Oportunidad',
    auth_subtitle: 'Un mercado curado para ofertas de inversión digitales — transparente, calificado y automatizado.',
    auth_feature_1: 'Cálculos de intereses y pagos automatizados',
    auth_feature_2: 'Empresas verificadas con calificaciones de transparencia',
    auth_feature_3: 'Mercado secundario — compra y vende posiciones',
    auth_demo: 'Cuentas de demostración',
    auth_wait: 'Por favor espere...',
    auth_error_generic: 'Algo salió mal',
    auth_demo_failed: 'Error en inicio de demo',

    // Marketplace
    mkt_title: 'Mercado de',
    mkt_title_2: 'Inversiones',
    mkt_active: 'ofertas activas',
    mkt_avg_return: 'rendimiento anual promedio',
    mkt_list_offering: 'Publicar Oferta',
    mkt_search: 'Buscar ofertas...',
    mkt_filters: 'Filtros',
    mkt_sort_newest: 'Más Recientes',
    mkt_sort_rate_desc: 'Mayor Rendimiento',
    mkt_sort_rate_asc: 'Menor Rendimiento',
    mkt_sort_funded: 'Más Financiados',
    mkt_category: 'Categoría',
    mkt_risk: 'Nivel de Riesgo',
    mkt_frequency: 'Frecuencia de Pago',
    mkt_no_results: 'Sin resultados para tu búsqueda',
    mkt_funded: 'Financiado',
    mkt_investors: 'inversores',
    mkt_annual_return: 'rendimiento anual',
    mkt_min: 'Mín',
    mkt_reviews: 'reseñas',
    mkt_all: 'Todos',

    // Offering card
    card_risk_low: 'riesgo bajo',
    card_risk_medium: 'riesgo medio',
    card_risk_high: 'riesgo alto',

    // Create Offering
    create_title: 'Crear',
    create_title_2: 'Oferta de Inversión',
    create_subtitle: 'Publica tu proyecto y atrae inversores con términos transparentes.',
    step_basic: 'Información',
    step_financial: 'Términos Financieros',
    step_files: 'Archivos',
    step_review: 'Revisión',
    step_payment: 'Pago',
    create_project_name: 'Nombre del Proyecto',
    create_project_name_hint: 'Un título claro y profesional para tu oferta',
    create_description: 'Descripción',
    create_description_hint: 'Describe el proyecto, sus metas y por qué los inversores deben confiar en él',
    create_description_placeholder: 'Descripción detallada de tu oferta de inversión...',
    create_category: 'Categoría',
    create_risk: 'Nivel de Riesgo',
    create_duration: 'Duración (meses)',
    create_duration_hint: '¿Por cuánto tiempo está abierta esta oferta?',
    create_payout_freq: 'Frecuencia de Pago',
    create_interest_rate: 'Tasa de Interés Anual (%)',
    create_interest_hint: 'El porcentaje de rendimiento anual ofrecido',
    create_pool: 'Tamaño Total del Fondo ($)',
    create_pool_hint: 'Capital máximo a recaudar',
    create_min_inv: 'Inversión Mínima ($)',
    create_max_inv: 'Inversión Máxima por Inversor ($)',
    create_max_inv_hint: 'Opcional — dejar en blanco para sin límite',
    create_files_title: 'Archivos y Medios',
    create_files_subtitle: 'Sube presentaciones, visuales y documentos de apoyo. Estos generan confianza.',
    create_drop: 'Arrastra archivos o haz clic para subir',
    create_drop_hint: 'PDF, PPT, PPTX, PNG, JPG, GIF · Máx 20MB cada uno',
    create_files_note: 'Los archivos son opcionales pero aumentan significativamente la confianza del inversor.',
    create_review_title: 'Revisar tu Oferta',
    create_submit: 'Publicar Oferta',
    create_submitting: 'Creando...',
    create_success_title: '¡Oferta Creada!',
    create_success_sub: 'Tu oferta fue enviada para revisión. Aparecerá en el mercado una vez aprobada.',
    create_my_projects: 'Mis Proyectos',
    create_view_offering: 'Ver Oferta',
    create_review_note: 'Tu oferta será revisada por nuestro equipo antes de publicarse en el mercado.',
    create_payment_subtitle: 'Comisiones de la plataforma por listar y mantener tu oferta de inversión en el mercado.',
    create_annual_fee: 'Comisión Anual de la Plataforma',
    create_per_year: 'por año',
    create_platform_fee: 'Comisión de la Plataforma',
    create_of_raised: 'de la cantidad recaudada',
    create_payment_info: 'Dirección de Cartera de Pago',
    create_payment_note: 'Se te pedirá que envíes el pago a esta dirección de cartera durante el pago.',
    btn_continue: 'Continuar',
    btn_back: 'Atrás',
    preview_title: 'Vista Previa de Rendimiento (por $1,000 invertidos)',
    preview_per_month: 'Por mes',
    preview_per_quarter: 'Por trimestre',
    preview_per_year: 'Por año',
    preview_annual: 'Rendimiento anual',
    preview_compounded: 'Compuesto 12 meses',

    // Offering detail
    detail_about: 'Sobre Esta Oferta',
    detail_docs: 'Documentos y Presentaciones',
    detail_ratings: 'Calificaciones de Inversores',
    detail_rate_btn: 'Calificar Proyecto',
    detail_no_ratings: 'Sin calificaciones aún — sé el primero en invertir y opinar.',
    detail_invest_btn: 'Invertir Ahora →',
    detail_signin_btn: 'Inicia Sesión para Invertir',
    detail_processing: 'Procesando...',
    detail_success: '¡Inversión Confirmada!',
    detail_success_sub: 'Tu posición ha sido abierta.',
    detail_view_portfolio: 'Ver Portafolio',
    detail_verified: 'Oferta Verificada',
    detail_verified_sub: 'Identidad empresarial y finanzas revisadas',
    detail_fully_funded: 'TOTALMENTE FINANCIADO',
    detail_inactive: 'Esta oferta no está aceptando inversiones actualmente.',
    detail_annual_rate: 'Tasa de interés anual',
    detail_duration: 'Duración',
    detail_investors: 'Inversores',
    detail_yields: 'genera',
    detail_funded_progress: 'Progreso de Financiamiento',
    detail_pool_remaining: 'Fondo Disponible',
    detail_payout: 'Pago',
    detail_min_investment: 'Inversión Mínima',
    detail_est_annual: 'Rendimiento anual est.',
    detail_per_period: 'Por',
    detail_submit_rating: 'Enviar Calificación',
    detail_payout_reliability: 'Confiabilidad de Pago',
    detail_transparency: 'Transparencia',
    detail_overall: 'Satisfacción General',
    detail_feedback_placeholder: 'Comparte tu experiencia (opcional)...',
    detail_breadcrumb: 'Mercado',

    // Portfolio
    portfolio_title: 'Mi',
    portfolio_title_2: 'Portafolio',
    portfolio_subtitle: 'Sigue tus inversiones, ganancias y pagos próximos.',
    portfolio_total_invested: 'Total Invertido',
    portfolio_value: 'Valor del Portafolio',
    portfolio_earned: 'Total Ganado',
    portfolio_roi: 'ROI General',
    portfolio_positions: 'Posiciones Activas',
    portfolio_no_investments: 'Sin inversiones activas.',
    portfolio_browse: 'Explorar el mercado →',
    portfolio_upcoming: 'Próximos Pagos',
    portfolio_invested: 'invertido',
    portfolio_current: 'valor actual',
    portfolio_earned_col: 'ganado',
    portfolio_list_btn: 'Listar',
    portfolio_list_title: 'Listar en Mercado Secundario',
    portfolio_list_sub: 'Establece tu precio de venta. Otros inversores podrán comprarlo.',
    portfolio_asking: 'Precio de Venta ($)',
    portfolio_asking_placeholder: 'Ingresa el precio',
    portfolio_cancel: 'Cancelar',
    portfolio_list_sale: 'Poner en Venta',

    // My Projects
    my_title: 'Mis',
    my_title_2: 'Ofertas',
    my_subtitle: 'Administra tus listados de inversión.',
    my_new: 'Nueva Oferta',
    my_no_offerings: 'Sin ofertas aún',
    my_no_sub: 'Crea tu primera oferta de inversión para comenzar a recaudar capital.',
    my_create: 'Crear Oferta',
    my_annual_rate: 'tasa anual',
    my_investors: 'inversores',

    // Secondary market
    sec_title: 'Mercado',
    sec_title_2: 'Secundario',
    sec_subtitle: 'Compra y vende posiciones de inversión existentes de otros inversores.',
    sec_no_listings: 'Sin listados disponibles',
    sec_no_sub: 'Vuelve más tarde o lista tus posiciones desde tu portafolio.',
    sec_asking: 'Precio de Venta',
    sec_original: 'Original',
    sec_current: 'Valor Actual',
    sec_interest: 'Tasa de Interés',
    sec_buy: 'Comprar por',
    sec_buying: 'Comprando...',
    sec_listed_by: 'Publicado por',

    // Admin
    admin_title: 'Panel de',
    admin_title_2: 'Administración',
    admin_subtitle: 'Monitorea la plataforma — proyectos, usuarios y pagos.',
    admin_tab_overview: 'Resumen',
    admin_tab_projects: 'Proyectos',
    admin_tab_users: 'Usuarios',
    admin_tab_payouts: 'Pagos',
    admin_total_users: 'Total Usuarios',
    admin_active_projects: 'Proyectos Activos',
    admin_total_capital: 'Capital Total',
    admin_pending_payouts: 'Pagos Pendientes',
    admin_recent_projects: 'Proyectos Recientes',
    admin_all_projects: 'Todos los Proyectos',
    admin_all_users: 'Todos los Usuarios',
    admin_all_payouts: 'Todos los Pagos',
    admin_pending: 'Pendientes',
    admin_processed: 'Procesados',
    admin_project_col: 'Proyecto',
    admin_rate_col: 'Tasa',
    admin_funded_col: 'Financiado',
    admin_investors_col: 'Inversores',
    admin_status_col: 'Estado',
    admin_actions_col: 'Acciones',
    admin_active_btn: 'Activar',
    admin_suspend_btn: 'Suspender',
    admin_restore_btn: 'Restaurar',
    admin_process_btn: 'Procesar',
    admin_fail_btn: 'Fallar',
    admin_of: 'de',
    admin_total: 'total',
    admin_due: 'pendiente',

    // Common
    loading: 'Cargando...',
    status_active: 'Activo',
    status_pending: 'Pendiente',
    status_closed: 'Cerrado',
    status_suspended: 'Suspendido',
    status_processed: 'Procesado',
    status_failed: 'Fallido',
    risk_low: 'bajo',
    risk_medium: 'medio',
    risk_high: 'alto',
    freq_monthly: 'mensual',
    freq_quarterly: 'trimestral',
    freq_annual: 'anual',
    cat_all: 'Todos',
    month: 'meses',
    copyright: '© 2026 · Mercado de Inversiones · Plataforma de Ofertas Digitales Reguladas',
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('im_lang') || 'en');

  const t = (key) => translations[lang][key] ?? translations['en'][key] ?? key;

  const toggle = () => {
    const next = lang === 'en' ? 'es' : 'en';
    setLang(next);
    localStorage.setItem('im_lang', next);
  };

  return (
    <LangContext.Provider value={{ lang, t, toggle }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
